image: continuumio/anaconda3



# ===== TEST PyWake debian=====
test_PyWake:  # name the job what we like
  image: continuumio/anaconda3
  stage:  # build, test, deploy defined by default [2]
    test
  script:
  # - pip install -e .
  - pytest
  tags:  # only runners with this tag can do the job [3]
  - ci-ubuntu


  
# ===== Check code style =====
check_code_style:  # name the job what we like
  stage:  # build, test, deploy defined by default [2]
    test
  script:
  # - pip install -e . --user
  - pycodestyle --ignore=E501,W504,E741 .
  tags:  # only runners with this tag can do the job [3]
  - python

