package:
  name: pyfuga
  version: 0.1.0

source:
  url: https://pypi.io/packages/source/p/pyfuga/pyfuga-0.1.0.tar.gz
  sha256: "e026b4ea8830eac676600468e21954a95c661307753faa5f21c2130de22c70cd"

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10,<3.15
    - pip
    - setuptools >=64
    - wheel
  run:
    - python >=3.10,<3.15
    - numpy >=1.26
    - scipy >=1.10
    - matplotlib >=3.10.8
    - xarray >=2025.6.1
    - tqdm >=4.67.3
    - h5netcdf >=1.8.1
    - h5py >=3.15.1
    - numba >=0.63.1

test:
  imports:
    - pyfuga
    - pyfuga.preluts_generator
  commands:
    - python -c "from pyfuga import get_luts"

about:
  home: https://gitlab.windenergy.dtu.dk/TOPFARM/PyFuga
  summary: Linearised CFD wake model (PyFuga)
  description: |
    Python implementation of the Fuga linearised CFD wake model and LUT generator.
  license: MIT
  license_file: LICENSE
  doc_url: https://topfarm.pages.windenergy.dtu.dk/PyFuga/main/index.html
  dev_url: https://gitlab.windenergy.dtu.dk/TOPFARM/PyFuga

extra:
  recipe-maintainers:
    - NilsGaukroger
